name: 05. Exposing Amazon DynamoDB Stream
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  deploy-elastic-container-registry:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
  build-and-push-webapp-image:
    runs-on: ubuntu-latest
    needs: deploy-elastic-container-registry
    steps:
    - name: Checkout
      uses: actions/checkout@v4
  deploy-infrastructure:
    runs-on: ubuntu-latest
    needs: [deploy-elastic-container-registry, build-and-push-webapp-image]
    steps:
    - name: Checkout
      uses: actions/checkout@v4