name: 06. Exposing Azure SQL Database Change Tracking
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
    deploy-infrastructure:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep
        id: deploy-bicep
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region:  westeurope
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          deploymentName: exposing-azure-sql-database-change-tracking
          template: ./infrastructure/exposing-azure-sql-database-change-tracking.bicep
          parameters: 'azureClientId=${{ secrets.AZURE_CLIENT_ID }}'
      - name: Create Azure SQL Database Contained User
        uses: Azure/sql-action@v2.3
        with:
          connection-string: 'Server=${{ steps.deploy-bicep.outputs.sqlServerFqdn }};Authentication=Active Directory Default; Encrypt=True; Database=${{ steps.deploy-bicep.outputs.sqlDatabaseName }}'
          path: ./infrastructure/create-azure-sql-database-contained-user.sql
          arguments: '-v ManagedIdentityName="${{ steps.deploy-bicep.outputs.managedIdentityName }}"'
      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear
    deploy-webapp:
      runs-on: ubuntu-latest
      needs: deploy-infrastructure
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore ./src/Demo.AspNetCore.Changefeed
      - name: Build
        run: dotnet build ./src/Demo.AspNetCore.Changefeed --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./src/Demo.AspNetCore.Changefeed --configuration Release --no-build --output ${DOTNET_ROOT}/app-exposing-change-feed
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-exposing-change-tracking
          package: ${{env.DOTNET_ROOT}}/app-exposing-change-feed
      - name: Azure Logout
        run: |
          az logout
          az cache purge
          az account clear